# Generated by Django 2.1 on 2019-06-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=50)),
                ('area_parent', models.ForeignKey(blank=True, null=True, on_delete=True, to='news.AreaInfo')),
            ],
            options={
                'verbose_name': '地区信息',
                'verbose_name_plural': '地区信息',
                'db_table': 'areainfo',
            },
        ),
    ]
