# Generated by Django 2.1 on 2019-06-06 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_areainfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_code', models.CharField(max_length=20)),
                ('area_name', models.CharField(max_length=20)),
                ('area_parent', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': '城区信息',
                'verbose_name_plural': '城区信息',
                'db_table': 'cityinfo',
            },
        ),
    ]
